hms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),  # Added url pattern for main app
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls')),
    # path('reserve/', include('reserve.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    # The field option name, should be unique as it is a unique identifier.
    # e.g. if you want to use the hyperlink of index page, don't use hardcoded url like
    # href="/main/" as if it is changed we have to change all the occurrences of it.
    # to solve this, use the value from name field. for above example use
    # href="{% url 'index' %}
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('rooms/', views.RoomListView.as_view(), name='rooms'),  # List of Rooms
    path('reservations/', views.ReservationListView.as_view(), name='reservations'),  # List of Reservations
    # <int:pk> takes the argument sent in urls.
    path('room/<int:pk>', views.RoomDetailView.as_view(), name='room-detail'),  # Detail of each room
    # Detail of each reservation
    path('reservation/<str:pk>', views.ReservationDetailView.as_view(), name='reservation-detail'),
    path('customer/<str:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),  # Detail of each customer
    path('staff/<str:pk>', views.StaffDetailView.as_view(), name='staff-detail'),  # Detail of staff
    path('profile/', login_required(views.ProfileView.as_view()), name='profile'),
    path('guests/', views.GuestListView.as_view(), name='guest-list'),
    path('reserve/', views.reserve, name='reserve'),  # For reservation
]

payment/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.payment_index, name='payment-index'),
    path('check_ins/', views.CheckInListView.as_view(), name='check_in-list'),
    path('check_in/<str:pk>', views.CheckInDetailView.as_view(), name='check_in-detail'),
    path('check_outs/', views.CheckOutListView.as_view(), name='check_out-list'),
    path('check_out/<str:pk>', views.CheckOutDetailView.as_view(), name='check_out-detail'),
]

payment/models.py
from math import ceil

from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.http import HttpRequest

from main.models import Reservation, Room


# Create your models here.
@python_2_unicode_compatible
class CheckIn(models.Model):
    id = models.CharField(max_length=50, primary_key=True, blank=True, editable=False)
    reservation = models.OneToOneField(Reservation, on_delete=models.CASCADE)
    rooms = models.CharField(max_length=50, editable=False, blank=True)
    initial_amount = models.PositiveSmallIntegerField(blank=True, editable=False)
    check_in_date_time = models.DateTimeField(default=timezone.now, editable=False)
    last_edited_on = models.DateTimeField(default=timezone.now, editable=False)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, editable=False)

    def __str__(self):
        return "%i - %s" % (self.reservation.reservation_id, self.reservation.customer)

    def get_absolute_url(self):
        return reverse('check_in-detail', args=[self.id])

    def save(self, *args, **kwargs):
        if not self.id:
            self.check_in_date_time = timezone.now()
            self.id = "checkin_" + str(self.reservation.reservation_id)
            self.rooms = ', '.join(room.room_no for room in self.reservation.room_set.all())
            self.initial_amount = 0
            for room in self.reservation.room_set.all():
                self.initial_amount += room.room_type.price
                for facility in room.facility.all():
                    self.initial_amount += facility.price
        else:
            reservation = get_object_or_404(CheckIn, id=self.id).reservation
            if self.reservation != reservation:
                self.reservation = reservation

        self.last_edited_on = timezone.now()
        super().save(*args, **kwargs)


@python_2_unicode_compatible
class CheckOut(models.Model):
    check_in = models.OneToOneField(CheckIn, on_delete=models.CASCADE)
    stay_duration = models.DurationField(null=True, editable=False)
    total_amount = models.PositiveSmallIntegerField(default=0, editable=False)
    pay_amount = models.PositiveSmallIntegerField(default=0, editable=False)
    check_out_date_time = models.DateTimeField(editable=False, null=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, editable=False)

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        if not self.id:
            self.check_out_date_time = timezone.now()
            self.stay_duration = self.check_out_date_time - self.check_in.check_in_date_time
            calculated_duration = timezone.timedelta(days=ceil(self.stay_duration.total_seconds() / 3600 / 24))
            self.total_amount = calculated_duration.days * self.check_in.initial_amount
            self.pay_amount = self.total_amount - self.check_in.initial_amount
        super().save(*args, **kwargs)

payment/forms.py
from django import forms

from .models import CheckOut


class CheckoutRequestForm(forms.ModelForm):
    class Meta:
        model = CheckOut
        fields = ['check_in']
        widgets = {'check_in': forms.HiddenInput()}

main/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.db import transaction, IntegrityError
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404  # For displaying in template
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views import generic

from .forms import Signup, ReservationForm, CheckInRequestForm
from .models import Room, Reservation, Customer, Staff  # Import Models


def index(request):
    """
    This is the view for homepage.
    This is a function based view.
    """
    page_title = _("Belview Management")  # For page title as well as heading
    total_num_rooms = Room.objects.all().count()
    available_num_rooms = Room.objects.exclude(reservation__isnull=False).count()
    total_num_reservations = Reservation.objects.all().count()
    total_num_staffs = Staff.objects.all().count()
    total_num_customers = Customer.objects.all().count()
    if total_num_reservations == 0:
        last_reserved_by = Reservation.objects.none()
    else:
        last_reserved_by = Reservation.objects.get_queryset().latest('reservation_date_time')

    return render(
        request,
        'index.html',
        # context is whatever sent to the template.
        # the index of the dictionary i.e. title in 'title': page_title
        # is used as variable in templates
        # where as the next one is the variable of this function
        {
            'title': page_title,
            'total_num_rooms': total_num_rooms,
            'available_num_rooms': available_num_rooms,
            'total_num_reservations': total_num_reservations,
            'total_num_staffs': total_num_staffs,
            'total_num_customers': total_num_customers,
            'last_reserved_by': last_reserved_by,
        }
    )


@transaction.atomic
def signup(request):
    title = "Signup"
    if request.user.is_authenticated:
        request.session.flush()
    if request.method == 'POST':
        form = Signup(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    staffs_group = get_object_or_404(Group, name__iexact="Staffs")
                    form.save()
                    staff_id = form.cleaned_data['staff_id']
                    username = form.cleaned_data['username']
                    s = get_object_or_404(Staff, staff_id__exact=staff_id)
                    s.user = get_object_or_404(User, username__iexact=username)
                    s.user.set_password(form.cleaned_data['password1'])
                    s.user.groups.add(staffs_group)
                    s.user.save()
                    s.save()
            except IntegrityError:
                raise Http404
            return redirect('index')
    else:
        form = Signup()

    return render(
        request,
        'signup.html', {
            'form': form, 'title': title},
    )


@permission_required('main.add_reservation', 'login', raise_exception=True)
@transaction.atomic
def reserve(request):
    title = "Add Reservation"
    reservation = Reservation.objects.none()
    if request.method == 'POST':
        reservation_form = ReservationForm(request.POST)
        if reservation_form.is_valid():
            try:
                with transaction.atomic():
                    customer = Customer(
                        first_name=reservation_form.cleaned_data.get('first_name'),
                        middle_name=reservation_form.cleaned_data.get('middle_name'),
                        last_name=reservation_form.cleaned_data.get('last_name'),
                        email_address=reservation_form.cleaned_data.get('email'),
                        contact_no=reservation_form.cleaned_data.get('contact_no'),
                        address=reservation_form.cleaned_data.get('address'),
                    )
                    customer.save()
                    staff = request.user
                    reservation = Reservation(
                        staff=get_object_or_404(Staff, user=staff),
                        customer=customer,
                        no_of_children=reservation_form.cleaned_data.get('no_of_children'),
                        no_of_adults=reservation_form.cleaned_data.get('no_of_adults'),
                        expected_arrival_date_time=reservation_form.cleaned_data.get('expected_arrival_date_time'),
                        expected_departure_date_time=reservation_form.cleaned_data.get('expected_departure_date_time'),
                        reservation_date_time=timezone.now(),
                    )
                    reservation.save()
                    for room in reservation_form.cleaned_data.get('rooms'):
                        room.reservation = reservation
                        room.save()
            except IntegrityError:
                raise Http404
            return render(
                request,
                'reserve_success.html', {
                    'reservation': reservation,
                }
            )
    else:
        reservation_form = ReservationForm()

    return render(
        request,
        'reserve.html', {
            'title': title,
            'reservation_form': reservation_form,
        }
    )


def reserve_success(request):
    pass


# For generic ListView or DetailView, the default templates should be stored in templates/{{app_name}}/{{template_name}}
# By default template_name = modelName_list || modelName_detail.
# eg room_list, room_detail
# @permission_required('main.can_view_staff')
class RoomListView(PermissionRequiredMixin, generic.ListView):
    """
    View for list of rooms.
    Implements generic ListView.
    """
    model = Room  # Chooses the model for listing objects
    paginate_by = 5  # By how many objects this has to be paginated
    title = _("Room List")  # This is used for title and heading
    permission_required = 'main.can_view_room'

    # By default only objects of the model are sent as context
    # However extra context can be passed using field extra_context
    # Here title is passed.

    extra_context = {'title': title}

    # By default:
    # template_name = room_list
    # if you want to change it, use field template_name
    # here don't do this, since it is already done as default.
    # for own views, it can be done.

    def get_queryset(self):
        filter_value = self.request.GET.get('filter', 'all')
        if filter_value == 'all':
            filter_value = 0
        elif filter_value == 'avail':
            filter_value = 1
        try:
            new_context = Room.objects.filter(availability__in=[filter_value, 1])
        except ValidationError:
            raise Http404(_("Wrong filter argument given."))
        return new_context

    def get_context_data(self, **kwargs):
        context = super(RoomListView, self).get_context_data(**kwargs)
        context['filter'] = self.request.GET.get('filter', 'all')
        return context


class RoomDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of room
    Implements generic DetailView
    """
    # The remaining are same as previous.
    model = Room
    title = _("Room Information")
    permission_required = 'main.can_view_room'
    extra_context = {'title': title}


class ReservationListView(PermissionRequiredMixin, generic.ListView, generic.FormView):
    """
        View for list of reservations.
        Implements generic ListView.
        """
    model = Reservation
    # queryset field selects the objects to be displayed by the query.
    # Here, the objects are displayed by reservation date time in descending order
    queryset = Reservation.objects.all().order_by('-reservation_date_time')
    title = _("Reservation List")
    paginate_by = 5
    allow_empty = True
    form_class = CheckInRequestForm
    success_url = reverse_lazy('check_in-list')
    permission_required = 'main.can_view_reservation'
    extra_context = {'title': title}

    @transaction.atomic
    def form_valid(self, form):
        try:
            with transaction.atomic():
                checkin = form.save(commit=False)
                checkin.user = self.request.user
                checkin.save()
        except IntegrityError:
            raise Http404
        return super().form_valid(form)


class ReservationDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of reservation
    Implements generic DetailView
    """
    model = Reservation
    title = _("Reservation Information")
    permission_required = 'main.can_view_reservation'
    raise_exception = True
    extra_context = {'title': title}


class CustomerDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of customer
    Implements generic DetailView
    """
    model = Customer
    title = _("Customer Information")
    permission_required = 'main.can_view_customer'
    raise_exception = True
    extra_context = {'title': title}


class StaffDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of staff
    Implements generic DetailView
    """
    model = Staff
    title = _("Staff Information")
    permission_required = 'main.can_view_staff_detail'
    extra_context = {'title': title}


class ProfileView(generic.TemplateView):
    template_name = 'profile.html'
    title = "Profile"
    extra_context = {'title': title}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['information'] = get_object_or_404(Staff, user=self.request.user)

main/templates/payment/checkin_detail.html
{% extends 'base.html' %}
{% block content-title %}
<h1>Check-In No: {{ checkin.id }}</h1>
{% endblock %}
<!-- TODO Work on FrontEnd -->
{% block main-content %}
<div class="row">
    <div class="card text-left col-md-6">
        <div class="card-header bg-primary text-blue"> Reservation:
            <a href="{% url 'reservation-detail' checkin.reservation.reservation_id %}" class="text-white">{{ checkin.reservation }}</a>
        </div>
        <div class="card-body bg-info text-blue">Rooms:
            {% for room in rooms %}
            <a href="{% url 'room-detail' room %}" class="text-white">{{ room }}</a>{% if not forloop.last %}, {% endif %}
            {% empty %}No rooms in the reservation.
            {% endfor %}
        </div>
        <div class="card-footer bg-info text-blue">Amount = {{ checkin.initial_amount }}</div>
        <div class="card-footer bg-info text-blue">Check-In Date-Time = {{ checkin.check_in_date_time }}</div>
        <!-- Only if customer has email -->
        <div class="card-footer bg-info text-blue">Last Edited On = {{ checkin.last_edited_on }}
        </div>
        <div class="card-footer bg-info text-blue">
            Checked In by: {% if staff.count == 0 %} {{ checkin.user }}{% else %}
            <a href="{% url 'staff-detail' staff.staff_id %}" class="text-white">{{ staff }}</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/payment/checkin_list.html
{% extends 'base.html' %}
<!--ToDo Work on Front end -->
{% block content-title %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block main-content %}
    {% if checkin_list %}
        <form action="" method="post" id="checkout">{% csrf_token %}
            {{ form }}
        </form>
        <table class="table table-hover">
            <thead>
            <tr bgcolor = "748949">
                <th>Check-In</th>
                <th>Reservation</th>
                <th>Rooms</th>
                <th>Paid Amount</th>
                <th>Check-In Date-Time</th>
                <th>Checkout?</th>
            </tr>
            </thead>
            <tbody>
            {% for check_in in checkin_list %}
                <tr bgcolor = "#7DFCF8">
                    <td>
                        <a href="{% url 'check_in-detail' check_in.id %}"> {{ check_in }}</a>
                    </td>
                    <td>{{ check_in.reservation }}</td>
                    <td>{% if check_in.rooms %}{{ check_in.rooms }}{% else %}-{% endif %}</td>
                    <td>{{ check_in.initial_amount }}</td>
                    <td>{{ check_in.check_in_date_time }}</td>
                    <td>
                        {% if not check_in.checkout %}
                            <button id="{{ check_in.id }}" type="button" class="btn btn-primary confirm-checkout"
                                    data-toggle="modal"
                                    data-target="#checkoutConfirmBox">
                                Checkout
                            </button>

                        {% else %}
                            <a class="btn btn-secondary"
                               href="{% url 'check_out-detail' check_in.checkout.id %}">Details</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="modal fade" id="checkoutConfirmBox">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Confirm Checkout</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <h5>Do you want to confirm checkout?</h5>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success" form="checkout">
                            Yes
                        </button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p>There are no check-ins.</p>
    {% endif %}
    {% block additional-javascript %}
        <script>
            $(document).ready(function () {
                $(".confirm-checkout").click(function () {
                    var $id = $(this).attr("id");
                    $("#id_check_in").attr("value", "" + $id);
                });
            });
            /*
            $(document).ready(function () {
                $(".confirm-checkout").mouseleave(function () {
                    $("#id_check_in").removeAttr("value");
                });
            });
            */
        </script>
    {% endblock %}
{% endblock %}

main/templates/payment/checkout_detail.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>Check-Out No: {{ checkout.id }}</h1>
{% endblock %}
<!-- TODO Work on FrontEnd -->
{% block main-content %}
    Check-In:
    <a href="{% url 'check_in-detail' checkout.check_in.id %}">{{ checkout.check_in }}</a> <br/>
    Stay Duration: {{ checkout.stay_duration }}<br/>
    Total Amount: {{ checkout.total_amount }}<br/>
    Pay Amount: {{ checkout.pay_amount }} <br/>
    Check-Out Date Time = {{ checkout.check_out_date_time }}<br/>
    Checked Out by:
    {% if staff.count == 0 %} {{ checkout.user }}{% else %}
        <a href="{% url 'staff-detail' staff.staff_id %}">{{ staff }}</a>
    {% endif %}
{% endblock %}

main/templates/payment/checkout_list.html
{% extends 'base.html' %}
<!--ToDo Work on Front end -->
{% block content-title %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block main-content %}
    {% if checkout_list %}
        <table class="table table-hover">
            <thead>
            <tr bgcolor = "748949">
                <th>Check-Out ID</th>
                <th>Related Check-in</th>
                <th>Stay Duration</th>
                <th>Total Amount</th>
                <th>Pay Amount</th>
                <th>Check-Out Date-Time</th>
            </tr>
            </thead>
            <tbody>
            {% for check_out in checkout_list %}
            <tr bgcolor = "#7DFCF8">
                <td><a href="{% url 'check_out-detail' check_out.id %}">{{ check_out }}</a></td>
                <td><a href="{% url 'check_in-detail' check_out.check_in.id %}">{{ check_out.check_in }}</a></td>
                <td>{{ check_out.stay_duration }}</td>
                <td>{{ check_out.total_amount }}</td>
                <td>{{ check_out.pay_amount }}</td>
                <td>{{ check_out.check_out_date_time }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no check-ins.</p>
    {% endif %}
{% endblock %}