hms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),  # Added url pattern for main app
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls')),
    # path('reserve/', include('reserve.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    # The field option name, should be unique as it is a unique identifier.
    # e.g. if you want to use the hyperlink of index page, don't use hardcoded url like
    # href="/main/" as if it is changed we have to change all the occurrences of it.
    # to solve this, use the value from name field. for above example use
    # href="{% url 'index' %}
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('rooms/', views.RoomListView.as_view(), name='rooms'),  # List of Rooms
    path('reservations/', views.ReservationListView.as_view(), name='reservations'),  # List of Reservations
    # <int:pk> takes the argument sent in urls.
    path('room/<int:pk>', views.RoomDetailView.as_view(), name='room-detail'),  # Detail of each room
    # Detail of each reservation
    path('reservation/<str:pk>', views.ReservationDetailView.as_view(), name='reservation-detail'),
    path('customer/<str:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),  # Detail of each customer
    path('staff/<str:pk>', views.StaffDetailView.as_view(), name='staff-detail'),  # Detail of staff
    path('profile/', login_required(views.ProfileView.as_view()), name='profile'),
    path('guests/', views.GuestListView.as_view(), name='guest-list'),
    path('reserve/', views.reserve, name='reserve'),  # For reservation
]

main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Staff(models.Model):
    """ Model for staffs """
    profile_picture = models.ImageField(upload_to='staff_img/', default='images/staff.png')
    staff_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=False, blank=True)
    last_name = models.CharField(max_length=50)
    contact_no = models.CharField(max_length=15)
    address = models.CharField(max_length=100)
    email_address = models.EmailField()
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, editable=False)

    class Meta:
        ordering = ['first_name', 'middle_name', 'last_name']
        permissions = (("can_view_staff", "Can view staff"), ('can_view_staff_detail', 'Can view staff detail'))

    def __str__(self):  # Unicode support
        return '({0}) {1} {2}'.format(self.staff_id, self.first_name, self.last_name)


@python_2_unicode_compatible
class Customer(models.Model):
    """Model for customers"""
    customer_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=False, blank=True)
    last_name = models.CharField(max_length=50)
    contact_no = models.CharField(max_length=15)
    address = models.CharField(max_length=100)
    email_address = models.EmailField(null=True, blank=True)

    class Meta:
        ordering = ['first_name', 'middle_name', 'last_name']
        permissions = (('can_view_customer', 'Can view customer'),)

    def get_absolute_url(self):
        """
        This generates the url for customer detail.
        'customer-detail' is the name of the url.
        Takes argument customer_id
        """
        return reverse('customer-detail', args=str([self.customer_id]))

    def __str__(self):
        return '({0}) {1} {2}'.format(self.customer_id, self.first_name, self.last_name)


@python_2_unicode_compatible
class Reservation(models.Model):
    """Models for reservations"""
    reservation_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, editable=False)
    no_of_children = models.PositiveSmallIntegerField(default=0)
    no_of_adults = models.PositiveSmallIntegerField(default=1)
    reservation_date_time = models.DateTimeField(default=timezone.now)
    expected_arrival_date_time = models.DateTimeField(default=timezone.now)
    expected_departure_date_time = models.DateTimeField(default=timezone.now)

    class Meta:
        permissions = (('can_view_reservation', 'Can view reservation'),
                       ('can_view_reservation_detail', 'Can view reservation detail'),)

    def get_absolute_url(self):
        return reverse('reservation-detail', args=str([self.reservation_id]))

    def __str__(self):
        return '({0}) {1} {2}'.format(self.reservation_id, self.customer.first_name, self.customer.last_name)


@python_2_unicode_compatible
class Room(models.Model):
    room_no = models.CharField(max_length=10, primary_key=True)
    room_type = models.ForeignKey('RoomType', null=False, blank=True, on_delete=models.CASCADE)
    availability = models.BooleanField(default=0)
    reservation = models.ForeignKey(Reservation, null=True, blank=True, on_delete=models.SET_NULL)
    facility = models.ManyToManyField('Facility')

    class Meta:
        ordering = ['room_no', ]
        permissions = (('can_view_room', 'Can view room'),)

    def __str__(self):
        return "%s - %s - Rs. %i" % (self.room_no, self.room_type.name, self.room_type.price)

    def display_facility(self):
        """
        This function should be defined since facility is many-to-many relationship
        It cannot be displayed directly on the admin panel for list_display
        """
        return ', '.join([facility.name for facility in self.facility.all()])

    display_facility.short_description = 'Facilities'

    def get_absolute_url(self):
        return reverse('room-detail', args=[self.room_no])

    def save(self, *args, **kwargs):  # Overriding default behaviour of save
        if self.reservation:  # If it is reserved, than it should not be available
            self.availability = 0
        else:
            self.availability = 1

        super().save(*args, **kwargs)


@python_2_unicode_compatible
class Facility(models.Model):
    name = models.CharField(max_length=25)
    price = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name_plural = 'Facilities'  # Otherwise admin panel shows Facilitys

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class RoomType(models.Model):
    name = models.CharField(max_length=25)
    price = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name

main/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.db import transaction, IntegrityError
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404  # For displaying in template
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views import generic

from .forms import Signup, ReservationForm, CheckInRequestForm
from .models import Room, Reservation, Customer, Staff  # Import Models


def index(request):
    """
    This is the view for homepage.
    This is a function based view.
    """
    page_title = _("Belview Management")  # For page title as well as heading
    total_num_rooms = Room.objects.all().count()
    available_num_rooms = Room.objects.exclude(reservation__isnull=False).count()
    total_num_reservations = Reservation.objects.all().count()
    total_num_staffs = Staff.objects.all().count()
    total_num_customers = Customer.objects.all().count()
    if total_num_reservations == 0:
        last_reserved_by = Reservation.objects.none()
    else:
        last_reserved_by = Reservation.objects.get_queryset().latest('reservation_date_time')

    return render(
        request,
        'index.html',
        # context is whatever sent to the template.
        # the index of the dictionary i.e. title in 'title': page_title
        # is used as variable in templates
        # where as the next one is the variable of this function
        {
            'title': page_title,
            'total_num_rooms': total_num_rooms,
            'available_num_rooms': available_num_rooms,
            'total_num_reservations': total_num_reservations,
            'total_num_staffs': total_num_staffs,
            'total_num_customers': total_num_customers,
            'last_reserved_by': last_reserved_by,
        }
    )


@transaction.atomic
def signup(request):
    title = "Signup"
    if request.user.is_authenticated:
        request.session.flush()
    if request.method == 'POST':
        form = Signup(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    staffs_group = get_object_or_404(Group, name__iexact="Staffs")
                    form.save()
                    staff_id = form.cleaned_data['staff_id']
                    username = form.cleaned_data['username']
                    s = get_object_or_404(Staff, staff_id__exact=staff_id)
                    s.user = get_object_or_404(User, username__iexact=username)
                    s.user.set_password(form.cleaned_data['password1'])
                    s.user.groups.add(staffs_group)
                    s.user.save()
                    s.save()
            except IntegrityError:
                raise Http404
            return redirect('index')
    else:
        form = Signup()

    return render(
        request,
        'signup.html', {
            'form': form, 'title': title},
    )


@permission_required('main.add_reservation', 'login', raise_exception=True)
@transaction.atomic
def reserve(request):
    title = "Add Reservation"
    reservation = Reservation.objects.none()
    if request.method == 'POST':
        reservation_form = ReservationForm(request.POST)
        if reservation_form.is_valid():
            try:
                with transaction.atomic():
                    customer = Customer(
                        first_name=reservation_form.cleaned_data.get('first_name'),
                        middle_name=reservation_form.cleaned_data.get('middle_name'),
                        last_name=reservation_form.cleaned_data.get('last_name'),
                        email_address=reservation_form.cleaned_data.get('email'),
                        contact_no=reservation_form.cleaned_data.get('contact_no'),
                        address=reservation_form.cleaned_data.get('address'),
                    )
                    customer.save()
                    staff = request.user
                    reservation = Reservation(
                        staff=get_object_or_404(Staff, user=staff),
                        customer=customer,
                        no_of_children=reservation_form.cleaned_data.get('no_of_children'),
                        no_of_adults=reservation_form.cleaned_data.get('no_of_adults'),
                        expected_arrival_date_time=reservation_form.cleaned_data.get('expected_arrival_date_time'),
                        expected_departure_date_time=reservation_form.cleaned_data.get('expected_departure_date_time'),
                        reservation_date_time=timezone.now(),
                    )
                    reservation.save()
                    for room in reservation_form.cleaned_data.get('rooms'):
                        room.reservation = reservation
                        room.save()
            except IntegrityError:
                raise Http404
            return render(
                request,
                'reserve_success.html', {
                    'reservation': reservation,
                }
            )
    else:
        reservation_form = ReservationForm()

    return render(
        request,
        'reserve.html', {
            'title': title,
            'reservation_form': reservation_form,
        }
    )


def reserve_success(request):
    pass


# For generic ListView or DetailView, the default templates should be stored in templates/{{app_name}}/{{template_name}}
# By default template_name = modelName_list || modelName_detail.
# eg room_list, room_detail
# @permission_required('main.can_view_staff')
class RoomListView(PermissionRequiredMixin, generic.ListView):
    """
    View for list of rooms.
    Implements generic ListView.
    """
    model = Room  # Chooses the model for listing objects
    paginate_by = 5  # By how many objects this has to be paginated
    title = _("Room List")  # This is used for title and heading
    permission_required = 'main.can_view_room'

    # By default only objects of the model are sent as context
    # However extra context can be passed using field extra_context
    # Here title is passed.

    extra_context = {'title': title}

    # By default:
    # template_name = room_list
    # if you want to change it, use field template_name
    # here don't do this, since it is already done as default.
    # for own views, it can be done.

    def get_queryset(self):
        filter_value = self.request.GET.get('filter', 'all')
        if filter_value == 'all':
            filter_value = 0
        elif filter_value == 'avail':
            filter_value = 1
        try:
            new_context = Room.objects.filter(availability__in=[filter_value, 1])
        except ValidationError:
            raise Http404(_("Wrong filter argument given."))
        return new_context

    def get_context_data(self, **kwargs):
        context = super(RoomListView, self).get_context_data(**kwargs)
        context['filter'] = self.request.GET.get('filter', 'all')
        return context


class RoomDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of room
    Implements generic DetailView
    """
    # The remaining are same as previous.
    model = Room
    title = _("Room Information")
    permission_required = 'main.can_view_room'
    extra_context = {'title': title}


class ReservationListView(PermissionRequiredMixin, generic.ListView, generic.FormView):
    """
        View for list of reservations.
        Implements generic ListView.
        """
    model = Reservation
    # queryset field selects the objects to be displayed by the query.
    # Here, the objects are displayed by reservation date time in descending order
    queryset = Reservation.objects.all().order_by('-reservation_date_time')
    title = _("Reservation List")
    paginate_by = 5
    allow_empty = True
    form_class = CheckInRequestForm
    success_url = reverse_lazy('check_in-list')
    permission_required = 'main.can_view_reservation'
    extra_context = {'title': title}

    @transaction.atomic
    def form_valid(self, form):
        try:
            with transaction.atomic():
                checkin = form.save(commit=False)
                checkin.user = self.request.user
                checkin.save()
        except IntegrityError:
            raise Http404
        return super().form_valid(form)


class ReservationDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of reservation
    Implements generic DetailView
    """
    model = Reservation
    title = _("Reservation Information")
    permission_required = 'main.can_view_reservation'
    raise_exception = True
    extra_context = {'title': title}


class CustomerDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of customer
    Implements generic DetailView
    """
    model = Customer
    title = _("Customer Information")
    permission_required = 'main.can_view_customer'
    raise_exception = True
    extra_context = {'title': title}


class StaffDetailView(PermissionRequiredMixin, generic.DetailView):
    """
    View for detail of staff
    Implements generic DetailView
    """
    model = Staff
    title = _("Staff Information")
    permission_required = 'main.can_view_staff_detail'
    extra_context = {'title': title}


class ProfileView(generic.TemplateView):
    template_name = 'profile.html'
    title = "Profile"
    extra_context = {'title': title}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['information'] = get_object_or_404(Staff, user=self.request.user)

main/templates/main/customer_detail.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block main-content %}
<div class="row">
    <div class="card text-left col-md-6">
        <div class="card-header bg-primary text-blue"> Id: {{ customer.customer_id }} </div>
        <div class="card-body bg-info text-blue">First Name: {{ customer.first_name }} <br>
                                Last Name: {{ customer.last_name }} </div>
        <div class="card-footer bg-info text-blue">Address: {{ customer.address }} </div>
        <div class="card-footer bg-info text-blue">Contact No: {{ customer.contact_no }}</div>
        <!-- Only if customer has email -->
        <div class="card-footer bg-info text-blue">{% if customer.email_address %}Email Address: {{ customer.email_address }} {% endif %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/guest_list.html
{% extends "base.html" %}

{% block main-content %}
    {% if guest_list %}
        <table class="table table-hover">
            <thead class="thead-dark">
            <tr>
                <th>Customer ID</th>
                <th>Customer Name</th>
            </tr>
            </thead>
            <tbody bgcolor = "#7DFCF8">
            {% for guest in guest_list %}
                <tr>
                    <td><a href="{% url 'customer-detail' guest.customer_id %}"> {{ guest.customer_id }}</a></td>
                    <td>{{ guest.first_name }} {{ guest.middle_name }} {{ guest.last_name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no guests.</p>
    {% endif %}
{% endblock %}

main/templates/main/reservation_detail.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>Reservation No. {{ reservation.reservation_id }} Details</h1>
{% endblock %}
{% block main-content %}
    <div class="row">
        <div class="card text-left col-md-6">
            <div class="card-header bg-primary text-blue">Customer: <a href="{% url 'customer-detail' reservation.customer_id %}" class="text-white">{{ reservation.customer }}</a>  </div>
            <div class="card-body bg-info text-blue">Staff: <a href="{% url 'staff-detail' reservation.staff_id %}" class="text-white">{{ reservation.staff }}</a><br>
                             </div>
            <div class="card-footer bg-info text-blue">No of Children: {{ reservation.no_of_children }}</div>
            <div class="card-footer bg-info text-blue"> No of Adults: {{ reservation.no_of_adults }}</div>
            <div class="card-footer bg-info text-blue">Reservation Date: {{ reservation.reservation_date_time }}</div>
            <div class="card-footer bg-info text-blue">  Expected Arrival: {{ reservation.expected_arrival_date_time }}</div>
            <div class="card-footer bg-info text-blue"> Expected Departure: {{ reservation.expected_departure_date_time }}</div>
            <div class="card-footer bg-info text-blue">{% if reservation.room_set.all %}
             Reserved Rooms:
                {% for room in reservation.room_set.all %}
                <strong><a href="{% url 'room-detail' room.room_no %}" class="text-white">{{ room }}</a>{% if not forloop.last %}
                , {% endif %}</strong>
            {% endfor %}
            {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

main/templates/main/reservation_list.html
{% extends 'base.html' %}

{% block main-content %}
    <form action="" method="post" id="checkin">{% csrf_token %}
        {{ form }}
    </form>
    {% if reservation_list %}
        <table class="table table-hover">
            <thead>
            <tr bgcolor = "#748949">
                <th>Reservation ID</th>
                <th>Customer</th>
                <th>Staff</th>
                <th>No of Children</th>
                <th>No of Adults</th>
                <th>Rooms</th>
                <th>Reservation Date Time</th>
                <th>Check In?</th>
            </tr>
            </thead>
            <tbody bgcolor = "7DFCF8">
            {% for reservation in reservation_list %}
                <tr>
                    <td>
                        <a href="{% url 'reservation-detail' reservation.reservation_id %}" class="text-white" >{{ reservation.reservation_id }}</a>
                    </td>
                    <td>{{ reservation.customer }}</td>
                    <td>{{ reservation.staff }}</td>
                    <td>{{ reservation.no_of_children }}</td>
                    <td>{{ reservation.no_of_adults }}</td>
                    <td>
                        {% for room in reservation.room_set.all %}
                            {{ room.room_no }}{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ reservation.reservation_date_time }}</td>
                    <td>{% if not reservation.checkin %}
                        <button id="{{ reservation.reservation_id }}" type="button" class="btn btn-primary confirm-checkin"
                                data-toggle="modal"
                                data-target="#checkInConfirmBox">
                            Check-In
                        </button>

                    {% else %}
                        <a class="btn btn-secondary"
                           href="{% url 'check_in-detail' reservation.checkin.id %}">Details</a>
                    {% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="modal fade" id="checkInConfirmBox">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Confirm Check-In</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <h5>Do you want to confirm check-in?</h5>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success" form="checkin">
                            Yes
                        </button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p>There are no reservations.</p>
    {% endif %}
{% endblock %}
{% block additional-javascript %}
    <script>
        $(document).ready(function () {
            $(".confirm-checkin").click(function () {
                var $id = $(this).attr("id");
                $("#id_reservation").attr("value", $id);
            });
        });
    </script>
{% endblock %}

main/templates/main/room_detail.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>{{ title }}</h1>
{% endblock %}
<!-- TODO Work on FrontEnd -->
{% block main-content %}
    <div class="row">
        <div class="card text-left col-md-6">

            <div class="card-header text-center">
                <!-- Room Photo -->
                {% load static %}
                <img src="#" alt="Room" style="width:200px; height=200px;">
            </div>
            <div class="card-header bg-info text-black">Room No: {{ room.room_no }}</div>
            <div class="card-body bg-info text-black">Room Type: {{ room.get_room_type_display }}</div>
            <div class="card-footer bg-info text-black">Availability : {% if room.availability %} Yes {% else %} No {% endif %}</div>
            <div class="card-footer bg-info text-black">  Facilities: {{ room.display_facility }} </div>

            <div class="card-footer bg-info text-black">
                {% if room.reservation %}
                    Reservation:
                    <a href="{% url 'reservation-detail' room.reservation_id %}"class="text-white">{{ room.reservation }} </a><br/>
                {% endif %}
            </div>
        </div>
{% endblock %}

main/templates/main/room_list.html
{% extends "base.html" %}

{% block main-content %}
    {% if room_list %}
        <table class="table table-hover">
            <thead class="thead-dark">
            <tr>
                <th>Room No</th>
                <th>Room Type</th>
                <th>Room Price</th>
                <th>Availability</th>
            </tr>
            </thead>
            <tbody bgcolor = "7DFCF8">
            {% for room in room_list %}
                <tr>
                    <td><a href="{% url 'room-detail' room.room_no %}"> {{ room.room_no }}</a></td>
                    <td>{{ room.room_type.name }}</td>
                    <td>{{ room.room_type.price }}</td>
                    <td>{% if room.availability %}
                        <span class="fa fa-check-circle" aria-hidden="true"> Available</span> {% else %}
                        <span class="fa fa-times-circle" aria-hidden="true"> Not Available</span>{% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <p>Filter By: <a href="{% url 'rooms' %}?filter={% if filter == 'all' %}avail{% else %}all{% endif %}">
            {% if filter == 'all' %}Available{% else %}All{% endif %}</a></p>
    {% else %}
        <p>There are no rooms.</p>
    {% endif %}
{% endblock %}

main/templates/main/staff_detail.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block main-content %}
    <div class="row">
        <div class="card text-left col-md-6">
            <div class="card-header text-center">
                {% load static %}
                <img src="{{ staff.profile_picture.url }}" alt="Staff Avatar" style="width:200px; height:200px;">
            </div>
            <div class="card-header bg-info text-white">Id: {{ staff.staff_id }}  </div>
            <div class="card-body bg-info text-white">First Name: {{ staff.first_name }}  <br>
                                Last Name:  {{ staff.last_name }}  </div>
            <div class="card-footer bg-info text-white">Contact No: {{ staff.contact_no }} </div>
            <div class="card-footer bg-info text-white">Address: {{ staff.address }}</div>
            <!-- Only if staff has email -->
            <div class="card-footer bg-info text-white">  {% if staff.email_address %}Email Address: {{ staff.email_address }} {% endif %}
            </div>
        </div>
    </div>
{% endblock %}